import {advance,money} from './engine.js';
export function openGuard(product,result,{tone='friendly',changeOnly=false,onAllow=()=>{},onSave=()=>{},onCancel=()=>{}}={}){
 const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;z-index:2147483647';const root=host.attachShadow({mode:'closed'});document.documentElement.append(host);const before=document.activeElement;
 const style=document.createElement('style');style.textContent=`*{box-sizing:border-box} .veil{position:fixed;inset:0;background:#152c29aa;display:grid;place-items:center;padding:18px;font:14px system-ui;color:#294838} .box{background:#fafbf6;max-width:510px;width:100%;padding:30px;border-radius:18px;box-shadow:0 30px 100px #0004;max-height:90vh;overflow:auto} h2{font-size:25px;margin:15px 0} p{line-height:1.7;color:#66785f} small{color:#88947e} button{font:inherit;cursor:pointer;padding:12px 16px;border-radius:8px;border:1px solid #d8e1ce;background:#fff;color:#3d5d35} .primary{background:#30543e;color:white;border-color:#30543e} .actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px} textarea{width:100%;min-height:105px;padding:12px;border:1px solid #cbd7bf;border-radius:8px;font:inherit} .tag{font-size:11px;letter-spacing:2px;color:#829370} .summary{background:#eef2e5;border-radius:9px;padding:13px;line-height:1.6} button:focus-visible,textarea:focus-visible{outline:3px solid #9fb975;outline-offset:2px}`;root.append(style);
 const veil=document.createElement('div');veil.className='veil';const box=document.createElement('section');box.className='box';box.role='dialog';box.setAttribute('aria-modal','true');box.setAttribute('aria-label','Cân nhắc trước khi mua');veil.append(box);root.append(veil);
 let state={phase:changeOnly||result.decision==='ALLOW'?'review':'question',index:0,answers:[],confirmations:0};
 const questions=['Món này giải quyết nhu cầu cụ thể nào của bạn?','Bạn đã có món nào thay thế được chưa? Vì sao chưa đủ?','Bạn dự kiến dùng bao nhiêu lần mỗi tháng, và sẽ điều chỉnh khoản chi nào?'];
 const close=()=>{host.remove();before?.focus?.();};
 function el(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;box.append(e);return e;}
 function button(parent,text,fn,primary=false){const b=document.createElement('button');b.textContent=text;if(primary)b.className='primary';b.onclick=fn;parent.append(b);return b;}
 function render(){box.replaceChildren();el('div','GUARDIAN · MỘT KHOẢNG DỪNG NHỎ','tag');el('p',`${product.name} · ${money(product.price)}`);const actions=document.createElement('div');actions.className='actions';
 if(changeOnly&&state.phase==='review'){
 el('h2','Chỉ cần xác nhận phần thay đổi');el('p','Mình nhớ bạn đã đồng ý mua món này. Không cần trả lời lại về nhu cầu.');el('div',result.reasons.join(' '),'summary');button(actions,'Đồng ý lựa chọn mới',()=>{onAllow([]);close();},true);button(actions,'Để tôi chọn lại',()=>{onCancel();close();});box.append(actions);
 }else if(state.phase==='question'){
 el('small',`Câu hỏi ${state.index+1}/3 · Không có câu trả lời đúng hay sai`);el('h2',questions[state.index]);el('p',result.reasons[state.index%result.reasons.length]);const input=el('textarea');input.maxLength=1000;input.setAttribute('aria-label','Câu trả lời về nhu cầu');const error=el('small');button(actions,'Tiếp tục',()=>{if(input.value.trim().length<8){error.textContent='Hãy mô tả cụ thể hơn một chút (ít nhất 8 ký tự).';return;}state=advance(state,input.value);render();},true);button(actions,'Để dành 24 giờ',()=>{onSave(state.answers);close();});box.append(actions);input.focus();
 }else if(state.phase==='review'){
 el('h2',result.decision==='ALLOW'?'Có vẻ phù hợp với ngân sách':'Cùng nhìn lại quyết định');el('p',result.reasons.join(' '));if(state.answers.length)el('div',state.answers.map((a,i)=>`${i+1}. ${a}`).join('\n'),'summary');el('p',result.decision==='ALLOW'?'Đây là đánh giá theo quy tắc và dữ liệu bạn cung cấp. Bạn vẫn nên kiểm tra chất lượng, phí giao hàng và lựa chọn sản phẩm.':'Câu trả lời đã được ghi nhận; bản cục bộ chưa xác thực được chất lượng lý do bằng mô hình ngôn ngữ. Khuyến nghị: chờ 24 giờ nếu nhu cầu còn chưa rõ.');button(actions,'Để dành suy nghĩ',()=>{onSave(state.answers);close();},true);button(actions,result.decision==='ALLOW'?'Cho phép tiếp tục':'Tôi vẫn muốn mua',()=>{if(result.decision==='ALLOW'){onAllow(state.answers);close();}else{state={...state,phase:'confirm',confirmations:0};render();}});box.append(actions);
 }else if(state.phase==='confirm'){
 const friendly=['Mình đã nhắc các điểm cần cân nhắc. Bạn vẫn thật sự muốn mua chứ?','Bạn chắc chắn muốn tiếp tục?','Bạn chấp nhận quyết định này, kể cả nếu sau đó thấy không cần thiết?'];const candid=['Tao cản lắm rồi mà mày vẫn thật sự muốn mua à?','Chắc chưa?','Không hối hận nhé?'];el('small',`Xác nhận ${state.confirmations+1}/3`);el('h2',(tone==='candid'?candid:friendly)[state.confirmations]);el('p','Bạn luôn có thể đổi ý. Xác nhận chỉ mở quyền tiếp tục, không đặt đơn hay thanh toán.');button(actions,'Có, tiếp tục',()=>{state=advance(state,'yes');if(state.phase==='allowed'){onAllow(state.answers);close();}else render();},true);button(actions,'Thôi, chưa mua',()=>{onCancel();close();});box.append(actions);
 }
 const cancel=el('button','Đóng · chưa mua');cancel.style.cssText='margin-top:18px;border:0;background:none;font-size:12px';cancel.onclick=()=>{onCancel();close();};
 queueMicrotask(()=>box.querySelector('textarea,button')?.focus());
 }
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();onCancel();close();}if(e.key==='Tab'){const all=[...box.querySelectorAll('button,textarea')];const i=all.indexOf(root.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&i===all.length-1){e.preventDefault();all[0].focus();}}});render();queueMicrotask(()=>box.querySelector('textarea,button')?.focus());
 return close;
}
