// Automatic companion. No network, telemetry or focus stealing on mount.
export function mountPet({onReview=()=>{},demo=false}={}){
 if(document.getElementById('guardian-pet'))return null;
 const host=document.createElement('div');host.id='guardian-pet';host.style.cssText='all:initial;position:fixed;right:24px;bottom:20px;z-index:2147483645;display:block;max-width:calc(100vw - 24px)';
 const root=host.attachShadow({mode:'open'});
 root.innerHTML=`<style>
 :host{color-scheme:light}*{box-sizing:border-box}.companion{font:13px/1.5 system-ui,sans-serif;color:#294739;width:285px;max-width:calc(100vw - 24px)}
 .bubble{background:#fffef8;border:1px solid #dae3cf;box-shadow:0 10px 38px #17382820;border-radius:18px 18px 5px 18px;padding:17px 18px;position:relative;margin-bottom:7px;animation:arrive .4s ease-out}.bubble:after{content:'';position:absolute;bottom:-8px;right:57px;width:13px;height:13px;transform:rotate(45deg);background:#fffef8;border-right:1px solid #dae3cf;border-bottom:1px solid #dae3cf}.label{font-size:9px;letter-spacing:1.6px;color:#89987a;margin-bottom:8px}.title{font-size:15px;font-weight:650;margin:0 0 7px}.message{font-size:12px;color:#6d7e62;margin:0;line-height:1.65;overflow-wrap:anywhere}.review{font:600 11px system-ui;color:#41613b;background:#edf3e4;border:0;border-radius:7px;padding:9px 12px;cursor:pointer;margin-top:12px}.stage{display:flex;justify-content:flex-end;align-items:flex-end;gap:10px}.badge{font-size:10px;color:#567348;background:#f7faef;border:1px solid #e1e8d8;border-radius:15px;padding:5px 10px;margin-bottom:22px}.badge:before{content:'●';color:#88ad60;margin-right:5px}
 .pet-button{position:relative;border:0;background:transparent;width:121px;height:130px;cursor:pointer;padding:0;flex-shrink:0}.body{position:absolute;left:17px;top:22px;width:88px;height:87px;border-radius:42% 43% 38% 39%;background:#bddc8f;border:2px solid #517345;box-shadow:inset -10px -8px 0 #a8c67c,inset 5px 5px 0 #d5ecb3;animation:breathe 3s ease-in-out infinite;transform-origin:bottom center}.ear{position:absolute;top:-16px;width:26px;height:34px;background:#bddc8f;border:2px solid #517345;border-radius:80% 80% 15% 20%;z-index:-1}.ear.left{left:8px;transform:rotate(-22deg)}.ear.right{right:8px;transform:rotate(22deg)}.eyes{position:absolute;top:32px;left:22px;display:flex;gap:23px}.eye{width:9px;height:13px;border-radius:50%;background:#294b38;animation:blink 5.2s infinite}.cheek{position:absolute;top:48px;background:#e3b9a0;width:13px;height:6px;border-radius:50%;opacity:.8}.cheek.left{left:12px}.cheek.right{right:12px}.mouth{position:absolute;left:36px;top:48px;width:13px;height:8px;border:2px solid #294b38;border-top:0;border-radius:0 0 12px 12px}.belly{position:absolute;bottom:9px;left:31px;width:25px;height:20px;background:#dfedc0;border-radius:50%;color:#648651;font:bold 15px Georgia;text-align:center}.foot{position:absolute;top:103px;width:29px;height:13px;background:#88aa6b;border:2px solid #517345;border-radius:50%}.foot.left{left:22px}.foot.right{right:21px}.shadow{position:absolute;bottom:8px;left:17px;width:90px;height:13px;background:#24473720;border-radius:50%;filter:blur(3px)}.leaf{position:absolute;top:8px;left:60px;width:16px;height:22px;border-radius:90% 0 90% 0;background:#4f7845;transform:rotate(20deg)}
 .companion[data-mood=alert] .body{background:#e8cf8b;box-shadow:inset -10px -8px 0 #d4b76f,inset 5px 5px 0 #f4e3b1}.companion[data-mood=alert] .bubble{border-color:#d9bd7e}.companion[data-mood=alert] .badge:before{color:#d3a24f}.companion[data-mood=guard] .body{animation:none}.companion[data-mood=guard] .eyes{transform:rotate(-6deg)}button:focus-visible{outline:3px solid #789c5f;outline-offset:3px;border-radius:12px}@keyframes breathe{50%{transform:translateY(-4px) rotate(2deg)}}@keyframes blink{0%,43%,47%,100%{transform:scaleY(1)}45%{transform:scaleY(.1)}}@keyframes arrive{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}@media(max-width:480px){.companion{width:245px}.bubble{padding:13px}.pet-button{transform:scale(.86);transform-origin:bottom right;height:117px}.badge{font-size:9px}}
 </style><section class="companion" data-mood="watch"><div class="bubble" role="status" aria-live="polite"><div class="label">GUARDIAN PET${demo?' · BẢN MÔ PHỎNG':''}</div><h2 class="title">Mình ở đây, cứ xem thoải mái.</h2><p class="message">Khi bạn định mua, mình sẽ cùng bạn cân nhắc một chút.</p><button class="review" type="button">Cùng xem món này</button></div><div class="stage"><span class="badge">Đang quan sát</span><button class="pet-button" type="button" aria-label="Trò chuyện với Guardian PET"><span class="shadow"></span><span class="foot left"></span><span class="foot right"></span><span class="body"><span class="ear left"></span><span class="ear right"></span><span class="eyes"><span class="eye"></span><span class="eye"></span></span><span class="cheek left"></span><span class="cheek right"></span><span class="mouth"></span><span class="belly">g</span></span><span class="leaf"></span></button></div></section>`;
 document.documentElement.append(host);root.querySelectorAll('button').forEach(b=>b.addEventListener('click',onReview));
 return {host,say(title,message,mood='watch',badge='Đang quan sát'){root.querySelector('.title').textContent=title;root.querySelector('.message').textContent=message;root.querySelector('.companion').dataset.mood=mood;root.querySelector('.badge').textContent=badge;},setReviewEnabled(enabled){root.querySelectorAll('button').forEach(b=>b.disabled=!enabled);},remove(){host.remove();}};
}
