const $=id=>document.getElementById(id);let snapshot={};
async function refresh(){snapshot=await chrome.storage.local.get(['recorderSettings','recorderEvents','recorderOrders','recorderSummary','recorderDropped','historyStatus']);const s={autoHistory:true,...snapshot.recorderSettings};$('enabled').checked=true;$('enabled').disabled=true;$('autoHistory').checked=s.autoHistory;$('cameraEnabled').checked=false;$('cameraEnabled').disabled=true;$('videoAnalysisEnabled').checked=false;$('videoAnalysisEnabled').disabled=true;$('status').textContent='● Luôn ghi nhận';$('localStatus').textContent='Local inference: tạm dừng';$('count').textContent=(snapshot.recorderEvents||[]).length;$('orders').textContent=snapshot.recorderSummary?.distinctOrders||0;$('history').textContent='Lịch sử: '+(snapshot.historyStatus?JSON.stringify(snapshot.historyStatus):'chưa đồng bộ');$('events').textContent=JSON.stringify((snapshot.recorderEvents||[]).slice(-20).reverse(),null,2);}
async function send(type,extra={}){try{const r=await chrome.runtime.sendMessage({type,...extra});if(r?.error)throw new Error(r.error);$('feedback').textContent=r.status||'Đã cập nhật.';await refresh();}catch(e){$('feedback').textContent=e.message;}}
$('autoHistory').addEventListener('change',()=>send('recorder-settings',{settings:{autoHistory:$('autoHistory').checked}}));
$('sync').onclick=()=>send('recorder-sync');$('clear').onclick=()=>send('recorder-clear');
function download(ext,body,type){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=`guardian-events-${new Date().toISOString().replace(/[:.]/g,'-')}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exported(){await refresh();return {schemaVersion:'1.0',exportedAt:new Date().toISOString(),coverage:'supported_sites_rendered_dom_partial',droppedEvents:snapshot.recorderDropped||0,events:snapshot.recorderEvents||[],orders:snapshot.recorderOrders||[],purchaseHabits:snapshot.recorderSummary||null,historyStatus:snapshot.historyStatus||null};}
$('json').onclick=async()=>download('json',JSON.stringify(await exported(),null,2),'application/json');
$('markdown').onclick=async()=>{const d=await exported();download('md',`# Guardian Recorder\n\nExport: ${d.exportedAt}\n\nCoverage: ${d.coverage}\n\nEvents: ${d.events.length}; dropped: ${d.droppedEvents}\n\n## Purchase habits\n\n\x60\x60\x60json\n${JSON.stringify(d.purchaseHabits,null,2)}\n\x60\x60\x60\n\n## Events\n\n${d.events.map(e=>'\x60\x60\x60json\n'+JSON.stringify(e,null,2)+'\n\x60\x60\x60').join('\n\n')}`,'text/markdown');};
chrome.storage.onChanged.addListener(refresh);refresh();
