(async()=>{
 const {clean,safeUrl,categoryOf,inferIntent,parseShopeeIdentity,createAttentionState,reduceAttention,attentionSnapshot,classifyPage}=await import(chrome.runtime.getURL('recorder-core.js'));
 const {extract}=await import(chrome.runtime.getURL('extractor.js'));
 let settings={autoHistory:true},url='',pageId='',product=null,activeMs=0,lastTick=Date.now(),lastInput=Date.now(),lastDwell=0,scrollLevel=0,scanPending=false;
 let attention=createAttentionState(Date.now()),lastAttentionEmit=0,lastPointer=null,pendingInteractions={pointerMoves:0,pointerDistance:0,clicks:0,scrolls:0,keydowns:0};
 const sessionId=crypto.randomUUID(),seen=new Set(),hoverTimers=new WeakMap();let historySignature='',historyRun=false,collectorTab=false;
 const privatePage=()=>/\/(messages|messaging|direct|login|buyer\/login|checkout\/payment)(\/|\?|$)/i.test(location.pathname);
 const allowed=()=>!privatePage();
 const privateNode=n=>!!n?.closest?.('[role="dialog"],[contenteditable="true"],[data-pagelet*="Chat"],[data-testid*="conversation"],[data-testid*="DM"]');
 const visible=n=>{if(document.hidden)return false;const r=n.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth;};
 const text=n=>privateNode(n)||n?.querySelector?.('[contenteditable],[role="dialog"],textarea,[data-pagelet*="Chat"],[data-testid*="conversation"],[data-testid*="DM"]')?'':clean(n?.innerText||n?.getAttribute?.('aria-label')||'');
 const site=()=>location.hostname.toLowerCase();const isShopee=()=>location.hostname.includes('shopee');
 function emit(type,data={},automatic=false,source=null){if(!allowed())return;const e={schemaVersion:'1.1',id:crypto.randomUUID(),timestamp:new Date().toISOString(),sessionId,pageId,site:site(),type,source:source||(automatic||collectorTab?'automatic_collection':'browser_observation'),page:{url:safeUrl(location.href),title:clean(document.title),siteType:classifyPage(location.href,document.title)},data,inference:inferIntent(type,data)};console.log(JSON.stringify(e));chrome.runtime.sendMessage({type:'recorder-event',event:e}).then(r=>{if(r?.event)console.log(JSON.stringify(r.event));if(r?.derived)console.log(JSON.stringify(r.derived));if(r?.error)console.warn(JSON.stringify({type:'recorder_storage_error',error:r.error}));}).catch(()=>{});}
 function badge(){let b=document.getElementById('guardian-recorder-status');if(!b){b=document.createElement('button');b.id='guardian-recorder-status';b.style.cssText='position:fixed;bottom:12px;left:12px;z-index:2147483647;padding:8px 12px;border:1px solid #476566;border-radius:20px;background:#103b36;color:white;font:12px system-ui;cursor:pointer';b.addEventListener('click',()=>chrome.runtime.sendMessage({type:'recorder-panel'}));document.documentElement.append(b);}b.textContent=privatePage()?'Recorder · Trang riêng tư':'● Recorder · Đang ghi';}
 function readProduct(){
  if(!isShopee()||!/(-i\.\d+\.\d+|\/product\/\d+\/\d+)/.test(location.pathname))return null;
  const raw=extract(document,location.href);if(!raw||raw.name==='Sản phẩm chưa xác định')return null;
  const identity=parseShopeeIdentity(location.href),unitPrice=Number.isFinite(raw.price)?raw.price:null,now=new Date().toISOString();
  return {productId:identity.productId,shopId:identity.shopId,name:clean(raw.name),url:safeUrl(location.href),selectedVariant:raw.variant||null,quantity:raw.quantity,unitPrice,price:unitPrice,priceMin:unitPrice,priceMax:unitPrice,shipping:null,total:unitPrice===null?null:unitPrice*raw.quantity,currency:'VND',category:categoryOf(raw.name),capturedAt:now,extractionVersion:'shopee-1.1',sources:[{field:'name',source:raw.source,confidence:raw.confidence},{field:'unitPrice',source:raw.source,confidence:raw.currentPriceVerified?'high':raw.confidence},{field:'selectedVariant',source:'semantic_selection',confidence:raw.variant?'high':'unknown'}],confidence:{overall:raw.currentPriceVerified?'high':raw.confidence,unitPrice:raw.currentPriceVerified?'high':raw.confidence},priceVerified:raw.currentPriceVerified,source:raw.source};
 }
 const productLink=n=>privateNode(n)?null:n?.closest?.('a[href*="-i."],a[href*="/product/"]');
 function linkProduct(n){const a=productLink(n);return a?{name:clean(text(a)||(!privateNode(a)&&!a.querySelector('[contenteditable]')?a.querySelector('img')?.alt:'')),url:safeUrl(a.href),category:categoryOf(text(a)||a.querySelector('img')?.alt)}:null;}
 function searchInput(n){return !privateNode(n)&&n instanceof HTMLInputElement&&n.type!=='password'&&(n.type==='search'||n.getAttribute('role')==='searchbox'||/tìm kiếm|search/i.test([n.placeholder,n.getAttribute('aria-label')].join(' ')));}
 function search(n){if(searchInput(n)&&clean(n.value))emit('search_submitted',{query:clean(n.value),evidence:'search_field_enter_or_submit'});}
 function historyRows(){
  const rows=[],links='a[href*="-i."],a[href*="/product/"]';
  for(const a of document.querySelectorAll(links)){
   if(privateNode(a))continue;
   let root=a.closest('[data-order-id],[data-orderid]');
   if(!root){for(let p=a.parentElement;p&&p!==document.body;p=p.parentElement){if(p.querySelector('a[href*="/order/"],a[href*="order_id="]')){root=p;break;}}}
   root ||= a.closest('article,section')||a.parentElement?.parentElement;
   const orderLink=root?.querySelector('a[href*="/order/"],a[href*="order_id="]');
   const orderId=root?.getAttribute('data-order-id')||root?.getAttribute('data-orderid')||orderLink?.href.match(/(?:order\/|order_id=)(\d+)/)?.[1]||null;
   let item=a;
   for(let p=a.parentElement;p&&p!==root?.parentElement;p=p.parentElement){if(new Set([...p.querySelectorAll(links)].map(n=>n.href)).size>1||p.querySelectorAll('[data-variant]').length>1||(text(p).match(/(?:^|\s)x\s*\d+\b/gi)||[]).length>1)break;item=p;if(p===root)break;}
   const body=text(root),itemText=text(item),match=a.href.match(/-i\.(\d+)\.(\d+)|\/product\/(\d+)\/(\d+)/);
   if(!match)continue;const name=clean(text(a)||(!privateNode(a)&&!a.querySelector('[contenteditable]')?a.querySelector('img')?.alt:''));if(!name)continue;
   const quantity=itemText.match(/(?:^|\s)x\s*(\d+)\b/i)?.[1];
   rows.push({orderId,productId:`${match[1]||match[3]}.${match[2]||match[4]}`,name,variant:clean(item.querySelector('[data-variant]')?.textContent)||null,quantity:quantity?Number(quantity):null,quantityVerified:!!quantity,status:/hoàn thành|completed|đã giao/i.test(body)?'completed':/đã hủy|cancelled/i.test(body)?'cancelled':'unknown',date:null,price:null,source:'rendered_dom',identityVerified:!!orderId});
  }
  return rows.slice(0,300);
 }
 function scanHistory(){if(!isShopee()||!location.pathname.startsWith('/user/purchase'))return;const rows=historyRows(),signature=JSON.stringify(rows);if(signature===historySignature)return;historySignature=signature;emit('purchase_history_snapshot',{rows,coverage:'partial_rendered_dom',status:rows.length?'rows_found':'no_rows_detected',note:'No rows may mean loading, empty history, login requirement or unsupported DOM.'},true);}
 function markInteraction(kind,count=1,distance=0){lastInput=Date.now();pendingInteractions[kind]+=count;if(kind==='pointerMoves')pendingInteractions.pointerDistance+=Math.max(0,Math.round(distance));}
 function sampleAttention(force=false){
  const now=Date.now(),interacted=Object.entries(pendingInteractions).some(([key,value])=>key!=='pointerDistance'&&value>0);
  attention=reduceAttention(attention,{now,visible:!document.hidden,focused:document.hasFocus(),interacted,idleThresholdMs:60000,...pendingInteractions});
  pendingInteractions={pointerMoves:0,pointerDistance:0,clicks:0,scrolls:0,keydowns:0};
  if(force||now-lastAttentionEmit>=15000){lastAttentionEmit=now;emit('attention_snapshot',{...attentionSnapshot(attention,now),measurement:'page_visibility_focus_and_aggregate_input',eyeTracking:false});}
 }
 async function collectHistory(){if(historyRun||!allowed())return;historyRun=true;const runPage=pageId;emit('history_sync_started',{coverage:'bounded_scan'},true);let steps=0;const timer=setInterval(()=>{if(!allowed()||pageId!==runPage||!location.pathname.startsWith('/user/purchase')){clearInterval(timer);historyRun=false;chrome.runtime.sendMessage({type:'recorder-sync-finished',status:'interrupted'}).catch(()=>{});return;}scanHistory();window.scrollBy(0,innerHeight);if(++steps>=8){clearInterval(timer);historyRun=false;emit('history_sync_finished',{coverage:'partial',scrollSteps:steps,rowsObserved:historyRows().length,note:'Only rendered rows; pagination and login are not bypassed.'},true);chrome.runtime.sendMessage({type:'recorder-sync-finished',status:'partial'}).catch(()=>{});}},1800);}
 function scan(){scanPending=false;if(!allowed())return;const next=readProduct();if(next&&JSON.stringify(next)!==JSON.stringify(product)){product=next;activeMs=0;lastDwell=0;emit('product_view',{product});}for(const n of [...document.querySelectorAll('a[href*="-i."],a[href*="/product/"],article,[role="article"]')].filter(n=>!privateNode(n)&&visible(n)).slice(0,200)){if(!visible(n))continue;const p=linkProduct(n),label=p?.name||text(n),key=(p?.url||label);if(!key||seen.has(key))continue;seen.add(key);if(seen.size>1000)seen.delete(seen.values().next().value);emit(p?'product_impression':'content_impression',p?{product:p}:{text:label,category:categoryOf(label),evidence:'visible_dom',attentionVerified:false});}scanHistory();}
 function navigate(){if(url===location.href)return;if(pageId)sampleAttention(true);url=location.href;pageId=crypto.randomUUID();product=null;activeMs=0;lastDwell=0;scrollLevel=0;seen.clear();historySignature='';lastTick=Date.now();attention=createAttentionState(lastTick);lastAttentionEmit=0;badge();if(!allowed())return;emit('page_view',{});const u=new URL(url),q=u.searchParams.get('keyword')||u.searchParams.get('q');if(q)emit('search_query_observed',{query:clean(q),evidence:'url_parameter'});if(/live|livestream/i.test(location.pathname))emit('livestream_context',{title:clean(document.title),products:[...document.querySelectorAll('a[href*="-i."]')].slice(0,20).map(linkProduct).filter(Boolean),evidence:'page_route_and_visible_dom',videoContentAnalyzed:false,analysisStatus:'not_requested'});scan();sampleAttention(true);if(isShopee())chrome.runtime.sendMessage({type:'recorder-shopee-visit'}).catch(()=>{});}
 document.addEventListener('click',e=>{if(!allowed()||privateNode(e.target)||e.target.closest?.('#guardian-recorder-status'))return;markInteraction('clicks');const n=e.target.closest?.('button,a,[role="button"],[role="tab"],select,input');if(!n)return;const sensitive=n.matches('input,select,textarea')||n.closest('[contenteditable="true"],[role="dialog"] input');const label=sensitive?'form_control':text(n);const kind=/^(thêm vào giỏ hàng|thêm vào giỏ|add to cart)$/i.test(label)?'cart_click':/^(mua ngay|buy now)$/i.test(label)?'buy_click':/^(đặt hàng|mua hàng|thanh toán|place order|checkout)$/i.test(label)?'checkout_click':'click';emit(kind,{label,tag:n.tagName.toLowerCase(),targetUrl:n.href?safeUrl(n.href):null,product:linkProduct(n)||product});},true);
 document.addEventListener('keydown',e=>{markInteraction('keydowns');if(e.key==='Enter')search(e.target);},true);
 document.addEventListener('submit',e=>{search(e.target.querySelector('input[type="search"],input[role="searchbox"]'));},true);
 document.addEventListener('change',e=>{if(!allowed()||privateNode(e.target))return;const n=e.target;if(n.matches?.('select,input[type="checkbox"],input[type="radio"]'))emit('selection_changed',{control:n.tagName.toLowerCase(),checked:n.checked??null,product});},true);
 document.addEventListener('pointerover',e=>{lastInput=Date.now();const a=productLink(e.target);if(!a||a.contains(e.relatedTarget)||hoverTimers.has(a))return;hoverTimers.set(a,setTimeout(()=>{hoverTimers.delete(a);if(document.hasFocus()&&!document.hidden)emit('product_hover',{product:linkProduct(a),hoverMs:1000});},1000));},true);
 document.addEventListener('pointerout',e=>{const a=productLink(e.target);if(a&&!a.contains(e.relatedTarget)){clearTimeout(hoverTimers.get(a));hoverTimers.delete(a);}},true);
 document.addEventListener('pointermove',e=>{if(privateNode(e.target))return;const distance=lastPointer?Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y):0;lastPointer={x:e.clientX,y:e.clientY};markInteraction('pointerMoves',1,distance);},{passive:true,capture:true});
 document.addEventListener('scroll',()=>{markInteraction('scrolls');if(!allowed())return;const max=document.documentElement.scrollHeight-innerHeight;const level=max>0?Math.floor(scrollY/max*4)*25:0;if(level>scrollLevel){scrollLevel=level;emit('scroll_depth',{percent:Math.min(100,level)});}}, {passive:true});
 for(const event of ['play','pause','ended','volumechange','seeked'])document.addEventListener(event,e=>{if(!privateNode(e.target)&&e.target instanceof HTMLMediaElement)emit('media_'+event,{currentTime:Math.round(e.target.currentTime||0),duration:Number.isFinite(e.target.duration)?Math.round(e.target.duration):null,muted:e.target.muted,context:clean(document.title),products:product?[product]:[],videoContentAnalyzed:false});},true);
 document.addEventListener('visibilitychange',()=>{sampleAttention(true);lastTick=Date.now();emit('visibility_changed',{visible:!document.hidden});});
 window.addEventListener('focus',()=>{sampleAttention(true);lastTick=Date.now();lastInput=Date.now();emit('page_focus_changed',{focused:true,...attentionSnapshot(attention,Date.now()),reason:'window_focus'});});window.addEventListener('blur',()=>{sampleAttention(true);lastTick=Date.now();emit('page_focus_changed',{focused:false,...attentionSnapshot(attention,Date.now()),reason:'window_blur'});});
 window.addEventListener('pagehide',()=>{sampleAttention(true);emit('page_session_ended',{activeMs,...attentionSnapshot(attention,Date.now()),reason:'pagehide'});});
 chrome.storage.onChanged.addListener(changes=>{if(changes.recorderSettings){settings={...settings,...changes.recorderSettings.newValue};badge();}});
 chrome.runtime.onMessage.addListener(m=>{if(m.type==='recorder-collect-history')collectHistory();else if(m.type==='desktop-intervention'&&m.message?.context?.documentId===pageId)console.log(JSON.stringify({type:'desktop_decision_received',messageId:m.message.messageId,leaseId:m.message.payload?.lease?.leaseId,documentId:pageId}));else if(m.type==='desktop-intervention-release')console.log(JSON.stringify({type:'desktop_decision_released',messageId:m.message?.messageId,leaseId:m.message?.payload?.leaseId}));});
 settings={...settings,...(await chrome.storage.local.get('recorderSettings')).recorderSettings};
 collectorTab=!!(await chrome.runtime.sendMessage({type:'recorder-ready'}).catch(()=>null))?.collect;
 badge();navigate();if(collectorTab)collectHistory();
 new MutationObserver(()=>{if(!scanPending){scanPending=true;setTimeout(scan,800);}}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});
 setInterval(()=>{navigate();sampleAttention();const now=Date.now(),dt=Math.min(now-lastTick,1500);lastTick=now;if(!allowed()||document.hidden||!document.hasFocus()||now-lastInput>60000)return;activeMs+=dt;if((product||/live|livestream/i.test(location.pathname))&&activeMs-lastDwell>=15000){lastDwell=activeMs;emit(product?'product_dwell':'livestream_dwell',{product,activeMs,measurement:'foreground_focused_nonidle_time',eyeTracking:false,videoContentAnalyzed:false});}scan();},1000);
})().catch(error=>console.warn('Guardian Recorder: reload extension and page.',error.message));
