import {createRequire} from 'node:module';import path from 'node:path';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE_JSON || new URL('../package.json', import.meta.url)),{chromium}=require('playwright');
const context=await chromium.launchPersistentContext(path.resolve('.test-recorder-social',String(Date.now())),{channel:'msedge',headless:true,args:[`--disable-extensions-except=${path.resolve('extension')}`,`--load-extension=${path.resolve('extension')}`]});
try{
const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).hostname;await worker.evaluate(()=>chrome.storage.local.clear());await worker.evaluate(()=>chrome.storage.local.set({recorderSettings:{enabled:true,autoHistory:false}}));
let historyFixturePending=false;const events=[],watch=p=>p.on('console',m=>{try{const e=JSON.parse(m.text());if(/^1\./.test(e.schemaVersion))events.push(e);}catch{}});context.on('page',page=>{watch(page);if(historyFixturePending){historyFixturePending=false;page.goto('https://shopee.vn/user/purchase/?type=3').catch(()=>{});}});
await context.route('https://www.facebook.com/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<html><title>Feed</title><body><article><p>Review tai nghe Bluetooth</p><button>Like</button></article><article>Public post <div contenteditable="true">PRIVATE_DRAFT_MUST_NOT_APPEAR</div></article><div role="dialog" aria-label="Chat"><article>PRIVATE_MESSAGE_MUST_NOT_APPEAR</article><button>PRIVATE_CHAT_BUTTON</button></div></body></html>'}));
await context.route('https://x.com/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<html><title>X</title><body><article>Đang tìm bàn phím mới <button>Like</button></article><input type="search"><video></video></body></html>'}));
await context.route('https://shopee.vn/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:r.request().url().includes('/user/purchase')?'<html><body><section data-order-id="9001">Hoàn thành <a href="/a-i.1.2">Tai nghe Bluetooth</a> x2</section><section data-order-id="9002">Hoàn thành <a href="/a-i.1.2">Tai nghe Bluetooth</a> x1</section></body></html>':'<html><title>Live tai nghe</title><body><h1>Live tai nghe</h1><a href="/a-i.1.2">Tai nghe Bluetooth</a><video></video></body></html>'}));
const p=await context.newPage();await p.goto('https://www.facebook.com/');await p.locator('#guardian-recorder-status').waitFor();await p.getByText('Like',{exact:true}).click();await p.getByText('PRIVATE_CHAT_BUTTON',{exact:true}).click();await p.waitForTimeout(1200);
assert.ok(events.some(e=>e.type==='content_impression'&&e.data.text.includes('Review tai nghe')));assert.ok(!JSON.stringify(events).includes('PRIVATE_'),'private chat overlay must be excluded');
await p.goto('https://x.com/home');await p.locator('input').fill('tai nghe');await p.locator('input').press('Enter');await p.evaluate(()=>document.querySelector('video').dispatchEvent(new Event('play')));await p.waitForTimeout(500);assert.ok(events.some(e=>e.site==='x.com'&&e.type==='search_submitted'));assert.ok(events.some(e=>e.type==='media_play'));
await p.goto('https://x.com/messages');await p.waitForTimeout(1000);const count=events.length;await p.locator('input').fill('PRIVATE_DIRECT');await p.locator('input').press('Enter');await p.waitForTimeout(400);assert.equal(events.length,count);
await p.goto('https://shopee.vn/live/123');await p.bringToFront();await p.waitForTimeout(16500);assert.ok(events.some(e=>e.type==='livestream_context'));assert.ok(events.some(e=>e.type==='livestream_dwell'));
const panel=await context.newPage();await panel.goto(`chrome-extension://${id}/recorder.html`);historyFixturePending=true;await panel.getByRole('button',{name:'Đọc lịch sử Shopee ngay'}).click();await panel.waitForFunction(()=>document.querySelector('#history').textContent.includes('partial'),{},{timeout:25000});
const data=await worker.evaluate(()=>chrome.storage.local.get(['recorderEvents','recorderSummary','historyTab']));assert.equal(data.recorderSummary.distinctOrders,2);assert.equal(data.recorderSummary.completedUnits,3);assert.equal(data.recorderSummary.products[0].repeatPurchase,true);assert.equal(data.historyTab,undefined);assert.ok(!context.pages().some(p=>p.url().includes('/user/purchase')),'owned history tab closes');assert.ok(data.recorderEvents.some(e=>e.type==='purchase_habits_updated'));
const dl=panel.waitForEvent('download');await panel.getByRole('button',{name:'Xuất JSON',exact:true}).click();const download=await dl;const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(exported.purchaseHabits.distinctOrders,2);
await fs.writeFile('docs/recorder-social-sample.json',JSON.stringify({dataOrigin:'synthetic_fixture_browser_run',...exported},null,2));await panel.screenshot({path:'docs/recorder-panel.png',fullPage:true});console.log(JSON.stringify({passed:true,eventTypes:[...new Set(exported.events.map(e=>e.type))],summary:exported.purchaseHabits}));
}catch(error){console.log('DIAGNOSTIC',JSON.stringify(await context.serviceWorkers()[0].evaluate(()=>chrome.storage.local.get(null))));console.log('TABS',context.pages().map(p=>p.url()));throw error;}finally{await context.close();}
