import {createRequire} from 'node:module';
import path from 'node:path';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE_JSON || new URL('../package.json', import.meta.url));
const {chromium}=require('playwright');
const channel=process.env.PLAYWRIGHT_CHANNEL ?? 'msedge';
const context=await chromium.launchPersistentContext(path.resolve('.test-recorder',String(Date.now())),{...(channel?{channel}:{}),headless:true,args:[`--disable-extensions-except=${path.resolve('extension')}`,`--load-extension=${path.resolve('extension')}`]});
try{
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
 await worker.evaluate(()=>chrome.storage.local.set({recorderSettings:{enabled:true,autoHistory:false}}));
 const p=await context.newPage(),events=[];
 p.on('console',m=>{try{const e=JSON.parse(m.text());if(/^1\./.test(e.schemaVersion))events.push(e);}catch{}});
 await context.route('https://shopee.vn/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:route.request().url().includes('/user/purchase')?`<html><body><h1>Đơn mua</h1><section data-order-id="1001"><span>Hoàn thành</span><a href="/tai-nghe-i.1.2">Tai nghe Bluetooth</a><span>x2</span></section></body></html>`:`<html><head><title>Tai nghe Bluetooth</title><script type="application/ld+json">{"@type":"Product","name":"Tai nghe Bluetooth","category":"Điện tử","offers":{"price":350000,"priceCurrency":"VND"}}</script></head><body><h1>Tai nghe Bluetooth</h1><div data-testid="product-price">₫420.000</div><button aria-pressed="true">Màu xanh</button><input aria-label="Số lượng" value="2"><input type="search" placeholder="Tìm kiếm"><input type="password" id="secret"><button id="cart">Thêm vào giỏ hàng</button><button id="buy" onclick="window.bought=true">Mua ngay</button><a href="/tai-nghe-i.1.2">Tai nghe Bluetooth</a><div style="height:2200px"></div></body></html>`}));
 await context.route('https://x.com/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:'<html><title>X fixture</title><body><article>Public post</article></body></html>'}));
 await p.goto('https://shopee.vn/tai-nghe-i.1.2');
 await p.waitForFunction(()=>!!document.querySelector('#guardian-recorder-status'),{},{timeout:8000});
 await p.locator('input[type=search]').fill('tai nghe chống ồn');await p.locator('input[type=search]').press('Enter');
 await p.mouse.move(20,20);await p.mouse.move(120,80);await p.keyboard.press('Shift');
 await p.locator('#secret').fill('NEVER_RECORD_PASSWORD');
 await p.locator('#cart').click();await p.locator('#buy').click();
 assert.equal(await p.evaluate(()=>window.bought),true,'recorder must not block buying');
 await p.waitForTimeout(16500);
 const productView=events.find(e=>e.type==='product_view');
 assert.equal(productView.data.product.productId,'2');
 assert.equal(productView.data.product.shopId,'1');
 assert.equal(productView.data.product.unitPrice,420000);
 assert.equal(productView.data.product.selectedVariant,'Màu xanh');
 assert.equal(productView.data.product.quantity,2);
 assert.equal(productView.data.product.currency,'VND');
 assert.ok(productView.data.product.sources.length>0);
 const attention=events.filter(e=>e.type==='attention_snapshot').at(-1);
 assert.ok(attention.data.totalFocusedMs>0);
 assert.ok(attention.data.continuousFocusMs>0);
 assert.ok(attention.data.tabLifetimeMs>=attention.data.pageLifetimeMs);
 assert.ok(attention.data.interactions.pointerMoves>=2);
 assert.ok(attention.data.interactions.keydowns>=1);
 assert.equal(JSON.stringify(attention).includes('Shift'),false);
 assert.ok(events.some(e=>e.type==='product_dwell'));
 assert.ok(events.some(e=>e.type==='search_submitted'&&e.data.query==='tai nghe chống ồn'));
 assert.ok(events.some(e=>e.type==='buy_click'&&e.inference.stage==='purchase_imminent'));
 assert.ok(!JSON.stringify(events).includes('NEVER_RECORD_PASSWORD'));
 const other=await context.newPage();await other.goto('https://x.com/home');await other.bringToFront();await p.bringToFront();await p.waitForTimeout(700);
 const tabEvents=await worker.evaluate(()=>chrome.storage.local.get('recorderEvents'));
 assert.ok(tabEvents.recorderEvents.some(e=>e.type==='tab_focus_changed'&&e.data.focused===true));
 assert.ok(tabEvents.recorderEvents.some(e=>e.type==='tab_focus_changed'&&e.data.focused===false));
 await p.evaluate(()=>history.pushState({},'','/search?keyword=keyboard&token=SECRET'));
 await p.waitForTimeout(1800);assert.ok(events.some(e=>e.type==='search_query_observed'&&e.data.query==='keyboard'));
 assert.ok(!JSON.stringify(events).includes('SECRET'));
 await p.goto('https://shopee.vn/user/purchase/?type=3');await p.waitForTimeout(2300);
 assert.ok(events.some(e=>e.type==='purchase_history_snapshot'&&e.data.rows[0]?.orderId==='1001'));
 await fs.mkdir('docs',{recursive:true});await fs.writeFile('docs/recorder-sample.json',JSON.stringify({dataOrigin:'synthetic_fixture_browser_run',events},null,2));
 console.log(JSON.stringify({passed:true,eventCount:events.length,types:[...new Set(events.map(e=>e.type))]}));
}finally{await context.close();}
