import {
  LEASE_DEFAULT_TTL_MS,
  type DeclaredSensor,
  type Lease,
  type ReleaseReason,
  type SessionTick,
  type SignalMessage,
  type SignalPayload
} from '@hostile-pet/contracts'
import type { BridgeHandler, HandlerContext } from './types'

/**
 * A stand-in for the rule engine, so the extension can be built and demonstrated before the
 * kernel exists. It is **not** policy.
 *
 * Two properties are deliberate, and both come from the repo's rules rather than from
 * convenience:
 *
 * 1. It is visibly a stub everywhere it surfaces. `copy.source` is `mock`, `demoMode` is
 *    true, the lease `reason` says the threshold is simulated, and every intervention log
 *    line carries `handler: 'mock'`. `docs/hackathon.md` §4 requires a mock to be admitted
 *    in the same breath as the claim it supports, and `AGENTS.md` non-negotiable 10 says a
 *    mock is never evidence that a sensor, tool or pack works.
 * 2. The placeholder line is **not** the pet's voice. `docs/tone.md` §1 decided that lines
 *    are generated by the model and checked by the validator; nothing here replaces that.
 *    The text says so out loud, so nobody can mistake it for a shipped line.
 *
 * What it does implement is the part the protocol needs proven: incremental ticks
 * accumulated kernel-side, replay rejection by `seq`, and a lease with a finite TTL and an
 * always-visible, clickable escape.
 */

export interface MockHandlerOptions {
  /** Qualifying accrued time that trips the gate. Lowered deliberately: this is a demo. */
  triggerActiveMs?: number
  leaseTtlMs?: number
  /** Plain language, always visible and clickable. Rendered verbatim by the surface. */
  escapeLabel?: string
  /** Placeholder, not product copy. See the note above. */
  copyText?: string
  locale?: string
  /** The rule id recorded on every lease this handler mints. */
  ruleId?: string
}

export interface MockStats {
  /** Page accumulators still being tracked. */
  trackedPages: number
  /** Gates currently open. At most one per page. */
  openGates: number
  /** Gates raised and seen released — the mock's whole reason for existing. */
  completedCycles: number
  /** Accrued qualifying milliseconds across every tracked page. */
  accruedMs: number
}

export interface MockHandler extends BridgeHandler {
  stats(): MockStats
}

const MOCK_DEFAULTS = {
  triggerActiveMs: 15_000,
  leaseTtlMs: LEASE_DEFAULT_TTL_MS,
  escapeLabel: 'Cho tôi qua',
  copyText: 'Câu thoại tạm của bản giả lập — chưa nối vào bộ sinh lời thoại.',
  locale: 'vi',
  ruleId: 'mock.daily_budget'
} as const

interface Accrual {
  accruedMs: number
  lastSeq: number
  gated: string | null
  cycles: number
}

/**
 * The one payload shape this handler understands. Written as a predicate so the caller
 * narrows instead of casting, and so adding a second schema to `signalPayloadSchemas` fails
 * here loudly rather than silently treating every payload as a tick.
 */
function isSessionTick(payload: SignalPayload): payload is { schema: 'signal.session.tick@1'; data: SessionTick } {
  return payload.schema === 'signal.session.tick@1'
}

export function createMockHandler(options: MockHandlerOptions = {}): MockHandler {
  const triggerActiveMs = options.triggerActiveMs ?? MOCK_DEFAULTS.triggerActiveMs
  const leaseTtlMs = options.leaseTtlMs ?? MOCK_DEFAULTS.leaseTtlMs
  const escapeLabel = options.escapeLabel ?? MOCK_DEFAULTS.escapeLabel
  const copyText = options.copyText ?? MOCK_DEFAULTS.copyText
  const locale = options.locale ?? MOCK_DEFAULTS.locale
  const ruleId = options.ruleId ?? MOCK_DEFAULTS.ruleId

  /** Keyed by `${connectionId}:${documentId}`: accrual is per page, never per socket. */
  const accruals = new Map<string, Accrual>()

  function gate(state: Accrual, ctx: HandlerContext, message: SignalMessage, sensor: DeclaredSensor): void {
    const seconds = Math.round(state.accruedMs / 1000)
    const lease = ctx.requestIntervention({
      scope: { tabId: message.context.tabId, documentId: message.context.documentId },
      windowFocused: message.context.windowFocused,
      packId: sensor.packId,
      ruleId,
      kind: 'bubble',
      ttlMs: leaseTtlMs,
      escapeLabel,
      demoMode: true,
      reason: `simulated threshold reached: ${seconds}s of qualifying time. This is a stand-in handler, not policy.`,
      copy: { text: copyText, locale, source: 'mock' }
    })
    // On failure the stage stays open so the next qualifying tick tries again: a silent
    // drop would look exactly like a gate that was raised.
    if (lease) state.gated = lease.leaseId
  }

  return {
    id: 'mock',

    onSignal(message, sensor, payload, ctx) {
      if (!isSessionTick(payload)) {
        ctx.log({
          event: 'bridge.signal.dropped',
          connectionId: ctx.connectionId,
          signal: message.type,
          reason: 'unhandled_schema',
          detail: 'the mock handler only understands signal.session.tick@1'
        })
        return
      }
      const tick = payload.data
      const key = `${ctx.connectionId}:${message.context.documentId}`
      const state = accruals.get(key) ?? { accruedMs: 0, lastSeq: -1, gated: null, cycles: 0 }

      // `seq` monotonicity is enforced here rather than in the bridge: the bridge decides
      // whether a message is well-formed and new, the accumulator decides what a counter
      // that went backwards means.
      if (tick.seq <= state.lastSeq) {
        ctx.log({
          event: 'bridge.signal.dropped',
          connectionId: ctx.connectionId,
          signal: message.type,
          reason: 'replay',
          detail: `seq ${tick.seq} is not greater than the last accepted seq ${state.lastSeq}`
        })
        return
      }
      state.lastSeq = tick.seq

      // `docs/architecture.md` §6: sleeping, unfocused or hidden time is not counted.
      const qualifies = tick.active && tick.visible && !tick.idle && message.context.windowFocused
      if (qualifies && state.gated === null) state.accruedMs += tick.activeMs
      accruals.set(key, state)

      if (state.gated === null && state.accruedMs >= triggerActiveMs) gate(state, ctx, message, sensor)
    },

    onReleased(lease: Lease, _reason: ReleaseReason) {
      for (const state of accruals.values()) {
        if (state.gated !== lease.leaseId) continue
        state.gated = null
        state.accruedMs = 0
        state.cycles += 1
      }
    },

    onDisconnected(connectionId: string) {
      for (const key of [...accruals.keys()]) {
        if (key.startsWith(`${connectionId}:`)) accruals.delete(key)
      }
    },

    stats(): MockStats {
      let accruedMs = 0
      let openGates = 0
      let completedCycles = 0
      for (const state of accruals.values()) {
        accruedMs += state.accruedMs
        if (state.gated !== null) openGates += 1
        completedCycles += state.cycles
      }
      return { trackedPages: accruals.size, openGates, completedCycles, accruedMs }
    }
  }
}
